---
title: "R Notebook"
output: html_notebook
---

# Final Project

## Data cleaning

```{r, message=FALSE}
library(tidyverse)
library(janitor)
library(ggplot2)

```

```{r, message=FALSE}
# core data files
comm_belong <- read_csv("../raw_data/shs_community_belonging.csv") %>% clean_names()
neighbourhood_rating <- read_csv("../raw_data/shs_neighbourhood_raiting.csv") %>% clean_names()
dist_blue_green <- read_csv("../raw_data/shs_dist_to_blue_or_green_space.csv") %>% clean_names()

```




```{r}
# additional files
data_zones <- read_csv("../raw_data/DataZone2011lookup_2022-05-05.csv") %>% clean_names() # Geography lookup tables 
derelict_urb_vacant <- read_csv("../raw_data/shs_derelict_and_urban_vacant_land.csv") %>% clean_names()
proximity_to_derelict <- read_csv("../raw_data/shs_population_living_in_close_proximity_to_a_derelict_site.csv") %>% clean_names()

```

```{r}
shs_data_bind <- comm_belong %>% bind_rows(dist_blue_green, neighbourhood_rating)

```


```{r}
# joining with data zones table to use real place names and make things more tangible
data_zones_trim <- data_zones %>% 
  select(la_code, la_name) %>% 
  distinct()

shs_data_la_join <- shs_data_bind %>% 
  left_join(data_zones_trim, by = c("feature_code" = "la_code"))

```


## Analysis

### Visualisation

```{r}
shs_data_la_join %>% 
  filter(walking_distance_to_nearest_greenspace != "All") %>% 
  ggplot() +
  aes(x = la_name, fill = walking_distance_to_nearest_greenspace) +
  geom_bar()

```

