---
title: "Final project documentation template - PDA"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    pdf_document: default
  word_document:
    toc: yes
---

# General

### Data Requirements

I can confirm that the data used in the project meets the following criteria:

| Criteria | Expected | Actual |
|----------|----------|--------|
| Number of rows | 5,000 | TBC |
| Sources of data | 3 | TBC |
| Data types | text data, numeric data and dates | TBC | 


# Template

## Context

#### Business intelligence and data-driven decision making

Q. What insights can the business/organisation gain from your analysis and how will your analysis help the business/organisation make better decisions? 

The analysis of the Scottish Household Survey data, with a focus on green space, will generate insights and recommendations for the Scottish Government in relation to:

- who does or doesn't have good access to green space?
- how far do they have to go for access?
- what characterises people with good access?

#### Domain knowledge and the business context

Q. Briefly describe the business/organisation and where your analysis fits within its aims/activity. 

The Scottish Household Survey (SHS), was commenced in 1999, and is a annual, cross-sectional and voluntary survey based on a sample of the general population (~10k per year) in private residences in Scotland, financed by the Scottish Government.

There are two parts to the survey, the household condition and random adult parts.

The aim of the survey is to understand the composition, characteristics and behaviours of Scottish households. 

The results will input into the Scottish Core Questions survey, Fairer Scotland Action Plan and National Framework (81 national indicators). These inputs will assist the Scottish Government in identifying policy areas for the future to improve social equality, inclusion and infrastructure such as transportation.

## Data

#### Internal and external data sources

Brief description of data sources both internal (provided by the organisation) and external (not sourced from the organisation's data).

The internal data files are:

- 'Distance to Green or Blue Space' 

The Scottish Household Survey (SHS) includes a question for adults on how long it would take them to walk to their nearest green (or blue) space. The blue element to this question is that canals for example are included within the open space types. This data is aggregated and presents the proportion of those responding the same way to a single question. The data contains character, data and numeric types.

- Various data files at the link: https://statistics.gov.scot/resource?uri=http%3A%2F%2Fstatistics.gov.scot%2Fdef%2Fconcept%2Ffolders%2Fthemes%2Fcommunity-wellbeing-and-social-environment

I used the 'Derelict and Urban Vacant Land' and 'Population living in close proximity to a derelict site' data files to inform discussion points around the potential conversion of areas to urban green space.
 
- I also used the '2011 Data Zone Lookup' .csv. file which contained the Scottish Government geography lookup tables used for aggregation, from 2011 data zones to higher level geographies.

The external data files are:

- A second dataset of information that had been scraped from academic sources was aggregated based on respondents similar responses to one or more questions. The number of people in each of these groupings was stated rather than a proportion as in 'Distance to Green or Blue Space'.

I also consulted external research articles for example, 'The Relationship between Social Cohesion and Urban Green Space: An Avenue for Health Promotion' (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6388234/).

#### Types of data

What kind of data did you work with? E.g. categorical and numerical data and their sub-types.

I worked with character, numeric and data types. The character categorical type was converted to a factor to allow for the decision tree analysis to be undertaken.

#### Data formats

What format did your data come in? E.g. all downloaded flat files (CSV) or any data from APIs, scraping etc.

All the files that were used were in the form of .csv as published on the Scottish Government website.

#### Data quality and bias

Briefly describe the quality of the data and whether you have any reasons to suggest the data is biased e.g. only data from a specific demographic even though a broader demographic would be of interest to the organisation.

The sample of the data is randomised based on post codes. In theory it's possible that voluntary survey is only undertaken by those with a specific opinion for example those unsatisfied with their nearest green space. However, data exploration revealed that respondents cover different groups for example all green space satisfaction ratings, age, sex, geographic location (incl. urban / rural) and employment type. 

## Ethics

#### Ethical issues in data sourcing and extraction

Do you have any ethical concerns regarding the sourcing and extraction of your data? 

The survey is both anonymous and confidential then results are aggregated before being published online by the Scottish Government. Therefore there are no ethical concerns regarding sourcing and extraction of the data.

#### Ethical implications of business requirements

Are there any ethical implications of the business requirements?

As the results of analysis and insights could inform policy decisions it is important that these are representative and fair across society. Decisions should be balanced so that the groups most in need benefit for example those without good access to green space could be a focus for the creation of new areas and the benefits that this may bring as opposed to those who already have good access to this resource.

## Analysis

#### Stages in the data analysis process

What were the main stages in your data analysis process?

- Familiarisation with the data, e.g. which variables had values that could be compared
- Summarised the data to understand the relative numbers and proportions to see if any normalisation would be required
- Exploration of the relationships between different variables, e.g. age vs distance to nearest green space
- Descriptive analytics, to summarise the data
- Predicitive analytics, using a decision tree to predict which groups of people were most likely to have good local access to green space

#### Tools for data analysis

What were the main tools you used for your analysis?

The main tools I used for analysis were:
- ggplot
- lapply() and rep() to disaggregate the data for modelling
- rpart to create the decision tree
- modelr to create predicions
- yardstick for the model accuracy testing using the predictions

#### Descriptive, diagnostic, predictive and prescriptive analysis

Please report under which of the below categories your analysis falls **and why** (can be more than one) 

::: {.emphasis}
**Descriptive Analytics** tells you what happened in the past.

I produced descriptive stats for example for the number of respondents in each year of the survey or the mean proportion and standard deviation values for green access categories by the urban or rural classification of the respondent.

**Diagnostic Analytics** helps you understand why something happened in the past.

**Predictive Analytics** predicts what is most likely to happen in the future.

I used a Decision Tree which is a type of predictive classification algorithm. 

The decision tree was used to characterise and predict which groups of people were most likely to have good local access to green space. 

I chose this method because I thought that the categorical data would be suited to the branching nature of the algorithm. That is that people are clearly in one group or another. This is as opposed to branching on a continuous numerical variable where the value upon which a split of the data occurs may not truly reflect the groups within the data, i.e. there is a range of behaviours either side of the split value and it's unlikely to be binary in nature. As the decision tree requires a binary variable at it's root node I engineered a varibale using the 'walking time to nearest green space' variable so that respondents with access equal to or <5min were assigned 'Yes' and those who weren't were 'No'.

To prepare the data I disaggregated it so that each individual respondent within a group was represented by a row in the data as opposed one row with the number of respondents stated at the end of the row. This disaggregation is important as the decision tree splits rows of the data based on their values for a specific variable and then allocates the rows down a branch. 

I the second dataset where the respondents were grouped based on similar responses as this was the only data that allowed for a model to be produced. Unfortunately this meant that apparently important variables such as urban or rural classification and SIMD percentile could not be included. However, I visualised various variable pairings in ggplot and ggpairs to see if I could subset based on pairing importance; i also removed variables that were irrelevant, e.g. year. In the end I used all the data in the second dataset where the respondents were grouped as this allowed the best opportunity to characterise based on a range of variables. Relationships are shown as far as the are significant so all variable combinations do not appear in the final decision tree.

**Prescriptive Analytics** recommends actions you can take to affect those outcomes.
:::


# PDA Outcomes

### Working with Data (J4Y6 35)

#### 1. Plan an analysis to provide business intelligence

-   1.1 Business intelligence and data-driven decision making
-   1.2 Domain knowledge and the business context
-   1.4 Internal and external data sources
-   1.5 Data quality
-   1.6 Stages in the data analysis process
-   1.7 Descriptive, diagnostic, predictive and prescriptive analysis
-   1.9 Ethical implications of business requirements
-   1.10 Tools for data analysis

#### 2. Extract data from a variety of sources

-   2.1 Tools for querying data sources
-   2.2 Types of data (categorical and numerical data and their sub-types)
-   2.3 Data formats
-   2.6 Data quality including data bias
-   2.7 Ethical issues in data sourcing and extraction

#### 4. Analyse data to provide business intelligence

-   4.7 Role of domain knowledge in interpreting analyses
